version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: aibos
      POSTGRES_PASSWORD: aibos
      POSTGRES_DB: aibos
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
volumes: { dbdata: {} }
