services:
  db:
    image: postgres:15
    container_name: aibos-postgres
    environment:
      POSTGRES_USER: aibos
      POSTGRES_PASSWORD: aibos
      POSTGRES_DB: aibos
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aibos -d aibos"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  dbdata:
    driver: local
