/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sales-invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post a Sales Invoice */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        id: string;
                        company_id: string;
                        customer_id: string;
                        /** Format: date-time */
                        doc_date: string;
                        currency: string;
                        lines: {
                            description: string;
                            qty: number;
                            unit_price: {
                                amount: string;
                                currency: string;
                            };
                            tax_code?: string;
                        }[];
                        totals: {
                            total: {
                                amount: string;
                                currency: string;
                            };
                            tax_total: {
                                amount: string;
                                currency: string;
                            };
                            grand_total: {
                                amount: string;
                                currency: string;
                            };
                        };
                    };
                };
            };
            responses: {
                /** @description Journal created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            journal_id: string;
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchase-invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post a Purchase Invoice */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        id: string;
                        company_id: string;
                        supplier_id: string;
                        /** Format: date-time */
                        doc_date: string;
                        currency: string;
                        lines: {
                            description: string;
                            qty: number;
                            unit_price: {
                                amount: string;
                                currency: string;
                            };
                            tax_code?: string;
                        }[];
                        totals: {
                            total: {
                                amount: string;
                                currency: string;
                            };
                            tax_total: {
                                amount: string;
                                currency: string;
                            };
                            grand_total: {
                                amount: string;
                                currency: string;
                            };
                        };
                    };
                };
            };
            responses: {
                /** @description Journal created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            journal_id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
